config/routes.rb
Rails.application.routes.draw do
  root to: 'seasons#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :home, only: [:index]
  resources :users, only: [:new, :create]
  resources :locations, only: [:index, :show]
  resources :jobs, only: [:index, :show]
  resources :seasons, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forage.rb
class Forage < ApplicationRecord
  has_many :location_forages
  has_many :locations, through: :location_forages
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :location_jobs
  has_many :locations, through: :location_jobs
  validates :job_name, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, :lat, :long, presence: true
  has_many :season_locations
  has_many :seasons, through: :season_locations
  has_many :location_jobs
  has_many :jobs, through: :location_jobs
  has_many :location_forages
  has_many :forages, through: :location_forages
end

app/models/location_forage.rb
class LocationForage < ApplicationRecord
  belongs_to :location
  belongs_to :forage
end

app/models/location_job.rb
class LocationJob < ApplicationRecord
  validates_inclusion_of :completed, in: [true, false]
  belongs_to :location
  belongs_to :job
end

app/models/season.rb
class Season < ApplicationRecord
  validates :name, :year, presence: true
  has_many :season_locations
  has_many :locations, through: :season_locations
end

app/models/season_location.rb
class SeasonLocation < ApplicationRecord
  belongs_to :season
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :first_name, :last_name, :role, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  enum role: [:user, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :require_user?
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user.admin? if current_user
  end

  def require_user?
    current_user || current_admin?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all
  end

  def show
    @season = Season.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    @return_path = params[:return]
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Logged in as #{@user.first_name}"
      redirect_to params[:session][:return_path]
    else
      flash[:login_error] = "The email or password you entered is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to items_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @return_path = params[:return] if params[:return]
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      session[:user_id] = @user.id
      redirect_to return_params
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end

  def return_params
    params.require(:user).permit(:return)[:return]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Home page

app/views/jobs/index.html.haml
%h1 Viewing All Jobs

%ul
  -@jobs.each do |job|
    %li
      =link_to job.job_name, job_path(job)

app/views/jobs/show.html.haml
%h1 Viewing: #{@job.job_name}

%th
  Job Stats:
  %tr #{@job.job_name}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HoneyTracker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    -# = controller.redirect_to login_path unless require_user? || request.path == login_path

    %nav.navbar.navbar-default
      .container-fluid
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              =link_to "Seasons", seasons_path
            %li
              =link_to "Locations", locations_path
            %li
              =link_to "Jobs", jobs_path
            %li
              =link_to "Login", login_path
    .container
      .row
        = yield

app/views/locations/index.html.haml
%h1 Viewing All Locations

%ul
  -@locations.each do |location|
    %li
      =link_to location.name, location_path(location)

app/views/locations/show.html.haml
%h1 Viewing: #{@location.name}

%h3 Location Details:
.row.col-md-6
  Forages:
  -@location.forages.each do |forage|
    =forage.forage_type

.row.col-md-6
  %iframe{src: "https://www.google.com/maps/embed/v1/place?key=AIzaSyBGJhcczudvxoZV90ePPIH6prQiNedeqa8&zoom=12&q=#{@location.lat}, #{@location.long} ", width: :"600", height: :"450", frameborder: :"0"}

app/views/seasons/index.html.haml
%h1 Seasons

%table.table.table-striped
  %thead
    %tr
      %th
        Season
      %th
        Status
      %th
        Locations Completed
      %th
        Jobs Completed
      %th
        Avg. Pull

  %tbody
    -@seasons.each do |season|
      %tr
        %td
          =link_to "#{season.name} #{season.year}", season_path(season)
        %td
          -# season.location.status
        %td
          -# season.locations where status == "complete"
        %td
          -# season.locations.jobs where status == "complete"
        %td
          -# season.locations.jobs.avg_rating

app/views/seasons/show.html.haml
%h1.table-stats #{@season.name} #{@season.year}

%table.table.table-striped
  %thead
    %tr
      %th
        Bee Yard
      %th
        Hives
      %th
        Supers
      %th
        Dead Hives
      %th
        Forage
      %th
        Jobs
  %tbody
    -@season.season_locations.each do |sl|
      %tr
        %td
          =sl.location.name
        %td
          =sl.num_hives
        %td
          =sl.num_supers
        %td
          =sl.num_dead
        %td
          -sl.location.forages.each do |forage|
            =forage.forage_type
        %td
          -sl.location.jobs.each do |job|
            =job.job_name